### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by TjerkZ** [TjerkZ/s3-dreamcatcher-site#1]
# Discription
As a user, I want to be able to login and see my infromation

# Tasks
- [x] login
- [x] logout
- [ ] deploy on server
- [x] Add auth0
- [ ] acount page with user information

# Acceptance Criteria
- [ ] Should be able to login
- [ ] Should be able to logout
- [ ] The account page is only accessible when logged in
